language: R
sudo: false
cache: packages
script:
- Rscript rmarkdown::render_site()
- touch _site/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master
