---
title: "Licensing and copyright information"
output:
  html_document:
    number_sections: false
    toc: no
---

The course material is licensed under the
[Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
and the course code is licensed under a [MIT License](LICENSE-MIT.html)
by [John Helveston](https://www.jhelvy.com).

In addition to my own developed material, I have also modified material from
other courses and workshops, including:

Name | Author | Links
--------- | --------- | ---
STAT 545 | U. of British Columbia | [course](http://stat545.com/); [github](https://github.com/STAT545-UBC)
R for Data Science | Garrett Grolemund & Hadley Wickham | [book](https://r4ds.had.co.nz/); [github](https://github.com/hadley/r4ds)
Handling Strings with R | Gaston Sanchez | [book](https://www.gastonsanchez.com/r4strings/); [github](https://github.com/gastonstat/r4strings)
EEB313: Quantitative Methods in R for Biology | [U of T Coders](https://uoftcoders.github.io/studyGroup/) | [course](https://uoftcoders.github.io/rcourse/index.html); [github](https://github.com/uoftcoders/rcourse)
Modern Dive | Chester Ismay & Albert Y. Kim | [course](https://moderndive.netlify.com/); [github](https://github.com/moderndive/moderndive_book)
Learning statistics with R | Danielle Navarro | [course](https://djnavarro.github.io/tidylsrbook/); [github](https://github.com/djnavarro/rbook)
R for Psychological Science | Danielle Navarro | [course](https://psyr.org/index.html); [github](https://github.com/djnavarro/psyr)
What They Forgot to Teach You About R | Jennifer Bryan & Jim Hester | [course](https://whattheyforgot.org/); [github](https://github.com/jennybc/what-they-forgot)
Introduction to Open Data Science | The Ocean Health Index Team | [course](http://ohi-science.org/data-science-training/); [github](https://github.com/OHI-Science/data-science-training)
Software Carpentry | [software-carpentry.org](https://software-carpentry.org/) | [lessons](https://software-carpentry.org/lessons/)
Data Analysis and Visualization in R for Ecologists | François Michonneau & Auriel Fournier | [course](https://datacarpentry.org/R-ecology-lesson/); [github](https://github.com/datacarpentry/R-ecology-lesson)
Data Analysis and Visualization in R _alpha_ | Data Carpentry contributors | [course](https://datacarpentry.org/R-genomics/index.html); [github](https://github.com/datacarpentry/R-genomics)
CMU 15-112: Fundamentals of Programming | [David Kosbie](http://www.kosbie.net/cmu/) & [Kelly Rivers](https://hcii.cmu.edu/people/kelly-rivers)| [Spring 2017 Course](http://www.kosbie.net/cmu/spring-17/15-112/)
R for Reproducible Research | Anna Krystalli | [course](https://annakrystalli.me/rrresearch/); [github](https://github.com/annakrystalli/rrresearch)
