---
title: "Resources"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.kable.NA = '')
```

# Getting Help

- [**Piazza**](piazza.com/gwu/fall2019/emse6574): Piazza can be used to ask quick questions and receive quick responses without attending office hours in person. This also enables other students to see answers to common questions. Questions on Piazza should be specific and include all needed information. For example, if your code has an error you don't understand, **include the code and the error message** in your question.
- **Office Hours**: Office hours let you ask questions to TAs and professors directly, and can help you understand concepts and debug programs that you're struggling with alone.
- While the University Library is not a stand in for TAs, you can schedule a consultation for general help with Coding, Programming, Data, Statistical, and GIS. See more at https://academiccommons.gwu.edu/writing-research-help

---

# Doing stuff in `R`

## Data Wrangling

- Wickham, Hadley. "R for Data Science"
[[free online](https://r4ds.had.co.nz/)],
[[buy on amazon](https://www.amazon.com/Data-Science-Transform-Visualize-Model/dp/1491910399)]

## Data Visualization

- Healy, Kieran. "Data Visualization: A practical introduction"
[[free online](http://socviz.co/)],
[[buy on amazon](https://www.amazon.com/Data-Visualization-Introduction-Kieran-Healy/dp/0691181624)]
- Wilke, Claus O. "Fundamentals of Data Visualization"
[[free online](https://serialmentor.com/dataviz/)],
[[buy on amazon](https://www.amazon.com/Fundamentals-Data-Visualization-Informative-Compelling/dp/1492031089)]
- [ggThemeAssist](https://github.com/calligross/ggthemeassist): Package for customizing plotting themes

## RStudio [cheatsheets](https://www.rstudio.com/resources/cheatsheets/)

- [RMarkdown](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)
- [Data wrangling with the `dplyr` library](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)
- [Data visualization with the `ggplot2` library](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf)

## RMarkdown

- [Table generator](http://www.tablesgenerator.com/): Create tables and get export code for multiple formats.
- [Markdown It](https://markdown-it.github.io): Quickly demo Markdown code.
- [RMarkdown guide](http://www.stat.cmu.edu/~cshalizi/rmarkdown/)

---

# Datasets

- [Kaggle](https://www.kaggle.com/datasets)
- [Google Dataset Search](https://toolbox.google.com/datasetsearch)
- [Tableau Community Forumss](https://community.tableau.com/docs/DOC-10635)
- [More datasets for teaching data science: The expanded `dslabs` package](https://simplystatistics.org/2019/07/19/more-datasets-for-teaching-data-science-the-expanded-dslabs-package/), by Amy Gill

---

# Helpful Tutorials

- [RStudio Primers](https://rstudio.cloud/learn/primers)
- [Tidyverse in R](https://www.datacamp.com/community/tutorials/tidyverse-tutorial-r)
- [Transitioning from Excel to R](https://trendct.org/2015/06/12/r-for-beginners-how-to-transition-from-excel-to-r/)

---

# Inspiration

- [The Links Between Open Science and Star Wars](https://medium.com/read-write-participate/open-science-and-star-wars-2577b8081e8f)
