---
title: "Course Schedule"
output:
  html_document:
    number_sections: false
    toc: no
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
rm(list=objects()) # start with a clean workspace
source("knitr_setup.R")
```

Here's your roadmap for the semester!

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(here)
library(gsheet)
options(knitr.kable.NA = '')
schedule <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1Rkc8vT75sqgYalZfbb1yS5N2-p1NSXw0-94A0PLzLl4/edit?usp=sharing')
# Define the first and last of class and finals start date
start  <- as.Date("2019/08/26")
end    <- as.Date("2019/12/09")
makeup <- as.Date("2019/12/11")
finals <- as.Date("2019/12/12")
# Format the dates
dates <- format(seq(start, end, by = "week"), format="%m/%d")
dates <- c(dates, format(c(makeup, finals), format="%m/%d"))
# Make the schedule data frame
schedule$Date <- dates
# Define the week
schedule$Week <- c(seq(1:(length(dates)-1)), (length(dates)-1))
schedule <- schedule[c('Week', 'Date', 'Event/Topics', 'Class Notes', 'Quizzes/Practice', 'Assignments')]
# Render the schedule as markdown
kable(schedule, format='markdown')
```
NOTE: In accordance with university policy, the final exam will be given during the final exam period and not the last week of the semester.

